USE [carrosdb]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE marca_tb(
	marca_id INT IDENTITY(1,1) NOT NULL,
	nome_marca VARCHAR (60) NOT NULL,
	logo VARCHAR (20) NOT NULL,
	CONSTRAINT [PK_marca_tb] PRIMARY KEY CLUSTERED 
	(
		[marca_id] ASC
	)
)
GO